spring:
  application:
    name: recipe_platform
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:recipe_platform}
    username: ${DB_USERNAME:recipe_platform}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    time-zone: Asia/Seoul